export const groupDB = [
	{
		iD: "yippee-sghouse",
		name: "SG house",
		ownerID: "yippee",
		ownerName: "ok2022",
		member: [yippee, jojo, peepy],
	},
];

export const userDB = [
	{
		userID: "yippee",
		username: "yippee",
		email: "test@ga.com",
		password: "ok2022",
		collections: ["yippee-sghouse"],
		items: [
			{
				productID: "10549750",
				product: "Fresh Milk - Low fat",
				expiryDate: "15-Jan-2022",
				Qty: 2,
				fav: true,
				cost: 5.95,
				brand: "Meiji",
				img: "https://media.nedigital.sg/fairprice/fpol/media/images/product/XL/10549750_XL1_20210903.jpg?w=1200&q=70",
				groupID: "yippee-sghouse",
			},
			{
				productID: "327454",
				product: "Hello Panda Biscuits with Chocolate",
				expiryDate: "15-Jun-2022",
				Qty: 10,
				fav: true,
				cost: 2,
				brand: "Meiji",
				img: "https://media.nedigital.sg/fairprice/fpol/media/images/product/XL/327454_XL1.jpg",
				groupID: "yippee-sghouse",
			},
			{
				productID: "10125886",
				product: "Luncheon Meat - Pork",
				expiryDate: "15-Mar-2023",
				Qty: 1,
				fav: false,
				cost: 3,
				brand: "Maling",
				img: "https://media.nedigital.sg/fairprice/fpol/media/images/product/XL/10125886_XL1_20210622.jpg?w=1200&q=70",
				groupID: "yippee-sghouse",
			},

			{
				productID: "d84843e2",
				product: "Eggs",
				expiryDate: "10-Jan-2022",
				Qty: 1,
				fav: false,
				cost: 2.3,
				brand: "Pasar",
				img: "https://media.nedigital.sg/fairprice/images/d84843e2-8e2f-46af-9152-4c0f3dd7b764/L2_Eggs_251021.jpg",
				groupID: "yippee-sghouse",
			},
			{
				productID: "13132899_XL1.jpg",
				product: "Hash brown",
				expiryDate: "01-Feb-2023",
				Qty: 2,
				fav: false,
				cost: 4.5,
				brand: "Tesco",
				img: "https://media.nedigital.sg/fairprice/fpol/media/images/product/XL/13132899_XL1.jpg",
				groupID: "yippee-sghouse",
			},
			{
				productID: "12528099",
				product: "Nuggets",
				expiryDate: "19-May-2023",
				Qty: 2,
				fav: false,
				cost: 8.8,
				brand: "Farmland",
				img: "https://media.nedigital.sg/fairprice/fpol/media/images/product/XL/12528099_XL1_20210203.jpg",
				groupID: "yippee-sghouse",
			},
			{
				productID: "13082985",
				product: "Pasta",
				expiryDate: "19-Mar-2022",
				Qty: 2,
				fav: false,
				cost: 2.6,
				brand: "Barilla",
				img: "https://media.nedigital.sg/fairprice/fpol/media/images/product/XL/13165420_XL1_20210915.jpg?w=1200&q=70",
				groupID: "yippee-sghouse",
			},
		],
	},
	{
		userID: "jojo",
		username: "jojo",
		email: "jojo@ga.com",
		password: "ok2023",
		collections: ["yippee-sghouse"],
		items: [
			{
				productID: "10549750",
				product: "Fresh Milk - Low fat",
				expiryDate: "08-Jan-2022",
				Qty: 1,
				fav: false,
				cost: 5.95,
				brand: "Meiji",
				img: "https://media.nedigital.sg/fairprice/fpol/media/images/product/XL/10549750_XL1_20210903.jpg?w=1200&q=70",
				groupID: "yippee-sghouse",
			},
			{
				productID: "327454",
				product: "Hello Panda Biscuits with Chocolate",
				expiryDate: "09-Mar-2022",
				Qty: 5,
				fav: true,
				cost: 2,
				brand: "Meiji",
				img: "https://media.nedigital.sg/fairprice/fpol/media/images/product/XL/327454_XL1.jpg",
				groupID: "yippee-sghouse",
			},
			{
				productID: "113655",
				product: "Tomato Pasta sauce",
				expiryDate: "04-Apr-2023",
				Qty: 1,
				fav: false,
				cost: 5,
				brand: "Prego",
				img: "https://media.nedigital.sg/fairprice/fpol/media/images/product/XL/113655_XL1_20210512.jpg",
				groupID: "yippee-sghouse",
			},

			{
				productID: "13096691",
				product: "Vit CC drink",
				expiryDate: "10-Jan-2022",
				Qty: 6,
				fav: true,
				cost: 5.5,
				brand: "Suntory",
				img: "https://media.nedigital.sg/fairprice/fpol/media/images/product/XL/13096691_XL1.jpg",
				groupID: "yippee-sghouse",
			},
			{
				productID: "11576937",
				product: "Belgian Chocolate",
				expiryDate: "01-Jul-2022",
				Qty: 2,
				fav: true,
				cost: 14.5,
				brand: "Haagen-Dazz",
				img: "hhttps://media.nedigital.sg/fairprice/fpol/media/images/product/XL/11576937_XL1_20210118.jpg",
				groupID: "yippee-sghouse",
			},
			{
				productID: "13048790",
				product: "Korean Instant Noodle",
				expiryDate: "19-Mar-2023",
				Qty: 1,
				fav: false,
				cost: 5,
				brand: "Samyang",
				img: "https://media.nedigital.sg/fairprice/fpol/media/images/product/XL/13048790_LXL1_20210428.jpg",
				groupID: "yippee-sghouse",
			},
			{
				productID: "11341847",
				product: "Abalone",
				expiryDate: "01-Jan-2023",
				Qty: 1,
				fav: false,
				cost: 56,
				brand: "Golden Chef",
				img: "https://media.nedigital.sg/fairprice/fpol/media/images/product/XL/11341847_XL1.jpg",
				groupID: "yippee-sghouse",
			},
		],
	},

	{
		userID: "peepy",
		username: "peepy",
		email: "peepy@ga.com",
		password: "ok1234",
		collections: ["yippee-sghouse"],
		items: [
			{
				productID: "cc01c9080c964c333df5c9c68db6243d",
				product: "Chilli sauce",
				expiryDate: "27-Jun-2022",
				Qty: 1,
				fav: false,
				cost: 2,
				brand: "Farmland",
				img: "https://sg-live.slatic.net/p/cc01c9080c964c333df5c9c68db6243d.jpg",
				groupID: "yippee-sghouse",
			},
			{
				productID: "327454",
				product: "Hello Panda Biscuits with Chocolate",
				expiryDate: "31-Dec-2021",
				Qty: 1,
				fav: true,
				cost: 2,
				brand: "Meiji",
				img: "https://media.nedigital.sg/fairprice/fpol/media/images/product/XL/327454_XL1.jpg",
				groupID: "yippee-sghouse",
			},
		],
	},
];
